version: 2.1
parameters:
  lockindex:
    type: string
    default: '1'

executors:
  core:
    docker:
      - image: satantime/puppeteer-node:16.15.1
    resource_class: medium
  a5:
    docker:
      - image: satantime/puppeteer-node:6.17.1
    resource_class: medium
  a6:
    docker:
      - image: satantime/puppeteer-node:8.17.0
    resource_class: medium
  a7:
    docker:
      - image: satantime/puppeteer-node:8.17.0
    resource_class: medium
  a8:
    docker:
      - image: satantime/puppeteer-node:10.24.1
    resource_class: medium
  a9:
    docker:
      - image: satantime/puppeteer-node:12.22.12
    resource_class: medium
  a10:
    docker:
      - image: satantime/puppeteer-node:12.22.12
    resource_class: medium
  a11:
    docker:
      - image: satantime/puppeteer-node:12.22.12
    resource_class: medium
  a12:
    docker:
      - image: satantime/puppeteer-node:12.22.12
    resource_class: medium
  a13:
    docker:
      - image: satantime/puppeteer-node:12.22.12
    resource_class: medium
  a14:
    docker:
      - image: satantime/puppeteer-node:16.15.1
    resource_class: medium

commands:
  install:
    parameters:
      dir:
        description: Directory in /e2e/
        type: string
    steps:
      - checkout
      - restore_cache:
          key: << parameters.dir >>-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/<< parameters.dir >>/package.json" }}-{{ checksum "e2e/<< parameters.dir >>/package-lock.json" }}
      - run:
          name: NPM Install
          command: |
            if [ ! -d "e2e/<< parameters.dir >>/node_modules/" ]; then
              npm run i:ci:<< parameters.dir >>
            fi
      - save_cache:
          key: << parameters.dir >>-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/<< parameters.dir >>/package.json" }}-{{ checksum "e2e/<< parameters.dir >>/package-lock.json" }}
          paths:
            - ./e2e/<< parameters.dir >>/node_modules

jobs:
  Core:
    executor: core
    steps:
      - checkout
      - restore_cache:
          key: root-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run:
          name: NPM Install
          command: |
            if [ ! -d "./node_modules/" ]; then
              npm ci --no-audit --legacy-peer-deps --no-optional && \
              ./node_modules/.bin/ngcc
            fi
      - save_cache:
          key: root-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Tests
          command: npm run test -- --code-coverage
      - run:
          name: Collecting Coverage coveralls.io
          command: ./node_modules/.bin/coveralls < test-reports/coverage/lcov/lcov.info
      - run:
          name: Collecting Coverage codecov.io
          command: ./node_modules/.bin/codecov -f test-reports/coverage/lcov/lcov.info --disable=gcov
      - store_test_results:
          path: ./test-reports
      - store_artifacts:
          path: ./test-reports/coverage
          prefix: coverage
      - persist_to_workspace:
          root: dist
          paths:
            - .
  E2E Install:
    parameters:
      node:
        type: executor
        default: core
      dir:
        type: string
    executor: << parameters.node >>
    steps:
      - install:
          dir: << parameters.dir >>
  'Angular 6':
    executor: a6
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a6-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a6/package.json" }}-{{ checksum "e2e/a6/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a6
      - run:
          name: Angular 6 E2E
          command: npm run e2e:a6
      - run:
          name: Angular 6 Build
          command: npm run b:a6
  'Angular 7':
    executor: a7
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a7-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a7/package.json" }}-{{ checksum "e2e/a7/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a7
      - run:
          name: Angular 7 E2E
          command: npm run e2e:a7
      - run:
          name: Angular 7 Build
          command: npm run b:a7
  'Angular 8':
    executor: a8
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a8-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a8/package.json" }}-{{ checksum "e2e/a8/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a8
      - run:
          name: Angular 8 E2E
          command: npm run e2e:a8
      - run:
          name: Angular 8 Build
          command: npm run b:a8
  'Angular 9 without Ivy':
    executor: a9
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a9-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a9/package.json" }}-{{ checksum "e2e/a9/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a9
      - run:
          name: Angular 9 E2E
          command: npm run e2e:a9:off
      - run:
          name: Angular 9 Build
          command: npm run b:a9:off
  'Angular 9 with Ivy':
    executor: a9
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a9-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a9/package.json" }}-{{ checksum "e2e/a9/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a9
      - run:
          name: Angular 9 E2E
          command: npm run e2e:a9:on
      - run:
          name: Angular 9 Build
          command: npm run b:a9:on
  'Angular 10 without Ivy':
    executor: a10
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a10-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a10/package.json" }}-{{ checksum "e2e/a10/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a10
      - run:
          name: Angular 10 E2E
          command: npm run e2e:a10:off
      - run:
          name: Angular 10 Build
          command: npm run b:a10:off
  'Angular 10 with Ivy':
    executor: a10
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a10-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a10/package.json" }}-{{ checksum "e2e/a10/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a10
      - run:
          name: Angular 10 E2E
          command: npm run e2e:a10:on
      - run:
          name: Angular 10 Build
          command: npm run b:a10:on
  'Angular 11 without Ivy':
    executor: a11
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a11-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a11/package.json" }}-{{ checksum "e2e/a11/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a11
      - run:
          name: Angular 11 E2E
          command: npm run e2e:a11:off
      - run:
          name: Angular 11 Build
          command: npm run b:a11:off
  'Angular 11 with Ivy':
    executor: a11
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a11-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a11/package.json" }}-{{ checksum "e2e/a11/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a11
      - run:
          name: Angular 11 E2E
          command: npm run e2e:a11:on
      - run:
          name: Angular 11 Build
          command: npm run b:a11:on
  'Angular 12 with Ivy':
    executor: a12
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a12-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a12/package.json" }}-{{ checksum "e2e/a12/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a12
      - run:
          name: Angular 12 E2E
          command: npm run e2e:a12:on
      - run:
          name: Angular 12 Build
          command: npm run b:a12:on
  'Angular 13 with Ivy':
    executor: a13
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a13-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a13/package.json" }}-{{ checksum "e2e/a13/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a13
      - run:
          name: Angular 13 E2E
          command: npm run e2e:a13
      - run:
          name: Angular 13 Build
          command: npm run b:a13
workflows:
  version: 2
  Testing:
    jobs:
      - Core:
          name: core

      # installing e2e
      - E2E Install:
          name: << matrix.dir >>:install
          node: << matrix.dir >>
          dir: << matrix.dir >>
          requires:
            - core
          matrix:
            parameters:
              dir:
                - a6
                - a7
                - a8
                - a9
                - a10
                - a11
                - a12
                - a13

      - 'Angular 6':
          name: a6:test
          requires:
            - a6:install
      - 'Angular 7':
          name: a7:test
          requires:
            - a7:install
      - 'Angular 8':
          name: a8:test
          requires:
            - a8:install
      - 'Angular 9 without Ivy':
          name: a9:test
          requires:
            - a9:install
      - 'Angular 9 with Ivy':
          name: a9:test:ivy
          requires:
            - a9:install
      - 'Angular 10 without Ivy':
          name: a10:test
          requires:
            - a10:install
      - 'Angular 10 with Ivy':
          name: a10:test:ivy
          requires:
            - a10:install
      - 'Angular 11 without Ivy':
          name: a11:test
          requires:
            - a11:install
      - 'Angular 11 with Ivy':
          name: a11:test:ivy
          requires:
            - a11:install
      - 'Angular 12 with Ivy':
          name: a12:test:ivy
          requires:
            - a12:install
      - 'Angular 13 with Ivy':
          name: a13:test:ivy
          requires:
            - a13:install
